/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class real_faulty_programs_real_bessj0 */

#ifndef _Included_real_faulty_programs_real_bessj0
#define _Included_real_faulty_programs_real_bessj0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     real_faulty_programs_real_bessj0
 * Method:    Produces_Error
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_real_1faulty_1programs_real_1bessj0_Produces_1Error
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
