/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class real_faulty_programs_real_cel */

#ifndef _Included_real_faulty_programs_real_cel
#define _Included_real_faulty_programs_real_cel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     real_faulty_programs_real_cel
 * Method:    Produces_Error
 * Signature: (DDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_real_1faulty_1programs_real_1cel_Produces_1Error
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
