/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class real_faulty_programs_real_golden */

#ifndef _Included_real_faulty_programs_real_golden
#define _Included_real_faulty_programs_real_golden
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     real_faulty_programs_real_golden
 * Method:    Produces_Error
 * Signature: (DDD)Z
 */
JNIEXPORT jboolean JNICALL Java_real_1faulty_1programs_real_1golden_Produces_1Error
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
